version: "3.8"

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_password
    networks:
      - salary_calculator_tier
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./build/libs/salary-calculator-1.0.0.jar:/opt/app.jar
    command: sh -c "/opt/wait-for-it.sh -t 0 db:5432 && java -jar /opt/app.jar"
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_JDBC_URL: jdbc:postgresql://db:5432/postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres_password
    depends_on:
      - db
    networks:
      - salary_calculator_tier

networks:
  salary_calculator_tier:
