version: "3.8"

services:
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:ro
    networks:
      - salary_calculator_tier
    ports:
      - "9920:9920"
  db:
    image: postgres:12-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_password
    networks:
      - salary_calculator_tier
  api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - ./build/libs/salary-calculator-1.0.0.jar:/opt/app.jar
    command: sh -c "/opt/wait-for-it.sh -t 0 db:5432 && java -jar /opt/app.jar"
    environment:
      POSTGRESQL_JDBC_URL: jdbc:postgresql://db:5432/postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres_password
    depends_on:
      - db
    networks:
      - salary_calculator_tier
  ui:
    build:
      context: .
      dockerfile: ./docker/ui.dockerfile
    container_name: ui
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./docker/http-reverse-proxy:/opt/http-reverse-proxy:ro
      - ./gui:/opt/salary_calculator
    environment:
      REACT_APP_API_URL: http://localhost:9920
    working_dir: /opt/salary_calculator
    user: salary_calculator
    ports:
      - "3000:3000"
    command: >
      sh -c '
        chown -R salary_calculator:salary_calculator . &&
        yarn &&
        yarn start
      '
    networks:
      - salary_calculator_tier

networks:
  salary_calculator_tier:
