version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: salary_calcularor
      POSTGRES_USER: salary_calculator_admin
      POSTGRES_PASSWORD: salary_calculator_password
    networks:
      - salary_calculator_tier
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./build/libs/salary-calculator-1.0.0.jar:/opt/app.jar
    command: java -jar /opt/app.jar
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_JDBC_URL: jdbc:postgresql://db:5432/salary_calculator
      POSTGRESQL_USERNAME: salary_calculator_admin
      POSTGRESQL_PASSWORD: salary_calculator_password
      WAIT_HOSTS: db:5432
    depends_on:
      - db
    networks:
      - salary_calculator_tier

networks:
  salary_calculator_tier:
