version: '3.7'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: employees
      MONGO_INITDB_ROOT_USERNAME: mongodb_admin
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./docker/mongodb/home/mongodb:/home/mongodb
    ports:
      - 27017:27017
    networks:
      - salary_calculator_tier
  api:
    build: .
    volumes:
      - ./build/libs/salary-calculator-1.0.0.jar:/app.jar
    command: java -jar /app.jar
    ports:
      - 8080:8080
    environment:
      MONGO_URI: mongodb://employees_admin:employees_password@db:27017/employees
      WAIT_HOSTS: db:27017
    links:
      - db
    depends_on:
      - db
    networks:
      - salary_calculator_tier

networks:
  salary_calculator_tier:
    driver: bridge
